name: MY FIRST GITHUB ACTION

on:
  push:
    branches:
      - master

env:
  NAME: "JOSHUA GBEGUDU K"
  ROLE: "SENIOR BIG DATA ENGINEER"
  PASSION: "TECH, FOOTBALL & MUSIC"


jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Echo Github Actions
        run: echo "My name is $NAME and i am a $ROLE. I am very passionate about $PASSION"
  
  post-build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Echo Post Build Steps
        run: echo "POSTBUILDS STEPS AFTER EXECUTION OF ABOVE STEPS"
