name: MY FIRST GITHUB ACTION

on:
  push:
    branches:
      - master

jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Echo Github Actions
        run: ls -al
  
  post-build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Echo Post Build Steps
        run: echo "POSTBUILDS STEPS AFTER EXECUTION OF ABOVE STEPS"
